### ISSUE TITLE
write back new meteor config fails: value must be a string

### ISSUE THREAD

**Issue by fkohrt** [n0emis/ansible-role-bigbluebutton#40]
I have set up a playbook as below, but it fails with the following message:
```
TASK [n0emis.bigbluebutton : write back new meteor config] *********************
fatal: [<hostname>]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ meteor  | to_nice_yaml }}): value must be a string"}
```

my `playbook.yml`:

```yaml
- hosts: webservers
  remote_user: <username>
  become: yes
  roles:
     - role: n0emis.bigbluebutton
       bbb_hostname: <hostname>
       bbb_letsencrypt_email: <email>
       bbb_coturn_secret: <coturn secret>
       bbb_greenlight_secret: <greenlight secret>
       bbb_greenlight_db_password: <greenlight db password>
       bbb_greenlight_default_registration: open
       bbb_disable_recordings: yes
       bbb_meteor:
         public:
           app:
             autoJoin: true
             skipCheck: true
       bbb_mute_on_start: yes
       bbb_freeswitch_ipv6: false
       bbb_greenlight_smtp:
         server: <smtp server>
         port: <smtp port>
         domain: <smtp domain>
         username: <smtp username>
         password: <smtp password>
         auth: plain
         starttls_auto: true
         sender: <smtp sender>
```

Is there something wrong with the playbook? Or is it there an issue with the role? Removing the `bbb_meteor` part completely still leads to that error...

**Comment by n0emis** [comment]
Hmm, I can't reproduce this. You can find the Variables I tested with under https://git.n0emis.eu/n0emis/home-automation/src/commit/792ba23b2a3f559bc4e9c5674a69ccf6ef996514/group_vars/bbb.yml#L26 . 

Which version of ansible are you using?

**Comment by fkohrt** [comment]
Sorry, been busy the last days; I had needed the server on short notice and therefore turned to a more manual solution, but I will look again if I can reproduce this (the system was a standard Azure VM).

**Comment by n0emis** [comment]
Coud you send me the values of the `meteor` variables before and after combining? You can do this by insterting 
```yaml
- name: extract config of meteor
  set_fact:
    meteor: "{{ r_meteor['content'] | b64decode | from_yaml }}"
  
- debug:
    msg: "{{ meteor }}"
    
- name: combine meteor config
  set_fact:
    meteor: "{{ meteor | combine(bbb_meteor, recursive=true) }}"
  
- debug:
    msg: "{{ meteor }}"
    
- name: write back new meteor config
  notify: restart bigbluebutton
  copy:
    content: '{{ meteor  | to_nice_yaml }}'
    dest: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
```
into the `tasks/config.yml`.
