### ISSUE TITLE
bbb_turn_servers doesn't work for me.

### ISSUE THREAD

**Issue by henriquebol** [n0emis/ansible-role-bigbluebutton#55]
I'm a little confused. In the example, it says bbb_turn_secret, but it doesn't exist. In default / main, a list with two items (with and without tls).

I tried everything: with with_items, same as the default / main, passing the parameters through bbb_coturn_ *, but without success.

How do I add my variables to bbb_turn_servers in the role (playbook)? Does anyone have any examples?

Sorry if it is something simple and that I am not seeing.

**Comment by DO1JLR** [comment]
Hi @henriquebol 

There are different ways to add variables to your ansible playbook. There are playbook variables that you define directly in your playbook. [-> docs.ansible.com](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html). Or you define them in the yaml files in your ``group_vars`` or ``host_vars`` directory. [-> docs.ansible.com](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html).

An example with playbook variables is:
```yaml
- hosts: servers
  roles:
    - n0emis.bigbluebutton
  vars:
    bbb_turn_secret: ee8d093109a9b273
    bbb_greenlight_secret: 107308d54ff4a5f
    bbb_greenlight_db_password: 2585c27c785e8895ec
    bbb_letsencrypt_email: mail@example.com
    bbb_turn_servers:
      - server: "{{ bbb_hostname }}"
        port: "{{ bbb_coturn_port }}"
        secret: "{{ bbb_coturn_secret }}"
        tls: false
      - server: "{{ bbb_hostname }}"
        port: "{{ bbb_coturn_port_tls }}"
        secret: "{{ bbb_coturn_secret }}"
        tls: true
      - server: "{{ ansible_fqdn }}"
        port: "{{ bbb_coturn_port_tls }}"
        secret: "{{ bbb_coturn_secret }}"
        tls: true
 ```

But I recomend to use `host_vars` and `group_vars`. For the group ``servers`` create the file in your ansible playbook:
```yaml
---
# filename: group_vars/servers.yml
bbb_letsencrypt_email: mail@example.com
bbb_turn_servers:
  - server: "{{ bbb_hostname }}"
    port: "{{ bbb_coturn_port }}"
    secret: "{{ bbb_coturn_secret }}"
    tls: false
  - server: "{{ bbb_hostname }}"
    port: "{{ bbb_coturn_port_tls }}"
    secret: "{{ bbb_coturn_secret }}"
    tls: true
  - server: "{{ ansible_fqdn }}"
    port: "{{ bbb_coturn_port_tls }}"
    secret: "{{ bbb_coturn_secret }}"
    tls: true
```
And define the individual secrets for each bbb server in his host_vars yaml file.
